#targets:
#  $default:
#    builders:
#      freezed:
#        options:
#          union_key: type
#          union_value_case: snake
#      json_serializable:
#        options:
#          explicit_to_json: true
#          field_rename: snake


targets:
  $default:
    builders:
      json_serializable:
        options:
#          field_rename: snake
          explicit_to_json: true
